IF
  Global("SpawnStart","AR5203",1)
  !Dead("Yaga01")  // ~Yaga-Shura~
  InActiveArea(Myself)
  !GlobalTimerNotExpired("mh#spawn_army", "ar5203")
  NumCreatureVsPartyLT("YSEXTRA2", %yaga_shura_army_count%)
  Difficulty(EASY)
THEN
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("ysfire02", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("hgtrl01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("hgsal01", 0)
END

IF
  Global("SpawnStart","AR5203",1)
  !Dead("Yaga01")  // ~Yaga-Shura~
  InActiveArea(Myself)
  !GlobalTimerNotExpired("mh#spawn_army", "ar5203")
  NumCreatureVsPartyLT("YSEXTRA2", %yaga_shura_army_count%)
  Difficulty(NORMAL)
THEN
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("ysfire02", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("hgtrl01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("hgsal01", 0)
END

IF
  Global("SpawnStart","AR5203",1)
  !Dead("Yaga01")  // ~Yaga-Shura~
  InActiveArea(Myself)
  !GlobalTimerNotExpired("mh#spawn_army", "ar5203")
  NumCreatureVsPartyLT("YSEXTRA2", %yaga_shura_army_count%)
  Difficulty(HARD)
THEN
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("ysfire02", 0)
    CreateCreatureOffscreen("ysfire02", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("hgtrl01", 0)
    CreateCreatureOffscreen("hgtrl01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("hgsal01", 0)
    CreateCreatureOffscreen("hgsal01", 0)
END

IF
  Global("SpawnStart","AR5203",1)
  !Dead("Yaga01")  // ~Yaga-Shura~
  InActiveArea(Myself)
  !GlobalTimerNotExpired("mh#spawn_army", "ar5203")
  NumCreatureVsPartyLT("YSEXTRA2", %yaga_shura_army_count%)
  Difficulty(HARDEST)
THEN
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("ysfire02", 0)
    CreateCreatureOffscreen("ysfire02", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
    CreateCreatureOffscreen("hellho01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold02", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
    CreateCreatureOffscreen("yssold01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("hgtrl01", 0)
    CreateCreatureOffscreen("hgtrl01", 0)
    CreateCreatureOffscreen("hgtrl01", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
    CreateCreatureOffscreen("yssold03", 0)
  RESPONSE #20
    SetGlobalTimer("mh#spawn_army", "ar5203", %yaga_shura_army_timer%)
    CreateCreatureOffscreen("hgsal01", 0)
    CreateCreatureOffscreen("hgsal01", 0)
    CreateCreatureOffscreen("hgsal01", 0)
END


