DEFINE_ACTION_FUNCTION setup_watchers_keep
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_animations"
    locbase	= "shared/animations"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_monsters"
    locbase	= "shared/monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "elemental_labs mighty_servant white_dracolich machine_ltm saladrex_battle orc_horde trial_dragon_battle"
    tra		= "watchers_keep"
  END
END	// setup_watchers_keep


