DEFINE_ACTION_FUNCTION setup_saradush
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_monsters"
    locbase	= "shared/monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_high_level"
    locbase	= "shared/high_level"
  END


  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "cursed_prison barracks_battle sewer_shadows"
    tra		= "saradush"
  END
END	// setup_saradush


