DEFINE_ACTION_FUNCTION setup_athkatla_liches
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "water_elementals"
    locbase	= "shared/monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "elder_elementals"
    locbase	= "shared/monsters"
  END


  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "shade_lich_battle elemental_lich_battle"
    tra		= "athkatla_liches"
  END

  // TODO: Kangaxx Battle
END	// setup_athkatla_liches


