DEFINE_ACTION_FUNCTION slime_resistances
BEGIN
  LAUNCH_ACTION_FUNCTION 2da_read
    STR_VAR
    file	= "slimes.2da"
    path	= "%MOD_FOLDER%/%component_loc%"
    type	= "table_header"
    case	= "lower"
    RET_ARRAY
    slimes	= array
    types	= rows
    stats	= columns
  END


  COPY_EXISTING_REGEXP "^.+\.cre$" "override"
    LPF struct_get STR_VAR arguments = "race" RET race_num = value END
    LPF struct_get STR_VAR arguments = "class" RET class_num = value END

    LOOKUP_IDS_SYMBOL_OF_INT race "race" race_num
    LOOKUP_IDS_SYMBOL_OF_INT class "class" class_num
    
    TO_LOWER race
    TO_LOWER class

    PATCH_MATCH "%SOURCE_RES%"
    WITH
      "jellspa" "bdslfs.."
      BEGIN
        TEXT_SPRINT class "fission_slime"
      END
      "pudden.."
      BEGIN
        TEXT_SPRINT class "dense_pudding"
      END
      "bdpuddbl"
      BEGIN
	TEXT_SPRINT class "black_pudding"
      END
      DEFAULT
    END

    PATCH_IF "%race%" STRING_EQUAL "slime"
         AND VARIABLE_IS_SET $types("%class%")
    BEGIN
      LPF struct_read RET_ARRAY m = struct END
      PHP_EACH stats AS stat=>discard
      BEGIN
        SET $m("%stat%") = $slimes("%class%" "%stat%")

	SET m_resist_magic_fire = m_resist_fire
	SET m_resist_magic_cold = m_resist_cold

        m.cre_strip_scripts{all}
        m_script_default := "WTARSGT"
	m.cre_add_items{"helmnoan(helmet)"|replace:i=1}

	PATCH_MATCH "%class%"
	WITH
	  "mustard_jelly"
	  BEGIN
	    m_hide_in_shadows = 90
	    m_move_silently = 90
	    m_script_race := "mh#musjl"
	    m.cre_add_items{mh#musjr(weapon1) mh#musjm(weapon2)|replace:i=1}
	  END
	  "ocre_jelly"
	  BEGIN
	    m.cre_add_items{mh#ochjr(weapon1) mh#ochjm(weapon2)|replace:i=1}
	  END
	  "grey_ooze"
	  BEGIN
	    m.cre_add_items{mh#grozr(weapon1) mh#grozm(weapon2)|replace:i=1}
          END
	  "green_slime"
	  BEGIN
	    //m.cre_add_items{jellgr1(weapon1) jellgr2(weapon2)|replace:i=1}
	  END
	  DEFAULT
	END
      END
      LPF struct_write STR_VAR struct = "m" END
    END

    BUT_ONLY_IF_IT_CHANGES
END	// slime_resistances


