IF
  OnCreation()
  Difficulty(EASIEST)
THEN
  RESPONSE #100
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
END

IF
  OnCreation()
  Difficulty(EASY)
THEN
  RESPONSE #100
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
END

IF
  OnCreation()
  Difficulty(NORMAL)
THEN
  RESPONSE #100
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
END

IF
  OnCreation()
  Difficulty(HARD)
THEN
  RESPONSE #100
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
END

IF
  OnCreation()
  Difficulty(HARDEST)
THEN
  RESPONSE #100
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
    CreateCreature("mh#spdhr", [-1.-1], 0)
END

IF
  True()
THEN
  RESPONSE #100
    DestroySelf()
END


