DEFINE_ACTION_FUNCTION gray_ooze_resources
BEGIN
  MAKE_PATCH
    patch_ability_inline=>~ability_dicenum=>0 ability_dicesize=>0 damage_type=>0 strength_bonus=>0~
    add_effect_inline=>~opcode=>12 target=>2 timing=>1 parameter2=>0x00010000 dicenum=>2 dicesize=>8~
  END

  LAUNCH_ACTION_FUNCTION clone_item
    STR_VAR
    item	= "oozegr1=>mh#grooz"
    edits	= "patch_data"
  END
END	// gray_ooze_resources


