ACTION_CLEAR_ARRAY ankheg

ACTION_DEFINE_ASSOCIATIVE_ARRAY ankheg
BEGIN
  strengthGT		=> 18
  strength_exGT		=> 75
  constitutionGT	=> 16
  dexterityGT		=> 14
  intelligenceLT	=> 3
  levelGT		=> "21 - thac0"
  enforce_saves		=> at_worst
  replace_items		=> "mh#ankhg(weapon1) mh#ankhg(weapon2) insect(ring)"
  insert_script_high	=> "mh#ankhg"
  strip_script		=> "ankheg"
  script_default	=> "wtasight"
END


