ACTION_CLEAR_ARRAY wyvern

ACTION_DEFINE_ASSOCIATIVE_ARRAY wyvern
BEGIN
  levelGT		=> "7 + %wyvern_hd_bonus%"
  enforce_hp		=> at_worst
  enforce_thac0		=> at_worst
  enforce_saves		=> at_worst
  hp_plus		=> 7
  enforce_xp		=> 3
  ac			=> "3 - %wyvern_ac_bonus%"
  strengthGT		=> 19
  dexterityGT		=> 16
  constitutionGT	=> 14
  replace_items		=> "wyvern1(weapon1) wyvern1(weapon2) wyvern2(shield)"
  strip_script		=> "wyvern"
  add_proficiencies	=> "2weapon=>3"
END
