DEFINE_ACTION_FUNCTION ramazith_battle
BEGIN
  MAKE_PATCH
    level1GT=>12
    enforce_thac0=>at_worst
    enforce_saves=>at_worst
    enforce_hp=>at_worst
  END

  LAUNCH_ACTION_FUNCTION edit_creature
    STR_VAR
    creature	= "ramazi"
    edits	= "patch_data"
  END

  LAUNCH_ACTION_FUNCTION extend
    STR_VAR
    script	= "ramazith"
    bottom	= "spawn_jellies"
    location	= "scripts"
  END
END	// ramazith_battle


