DEFINE_ACTION_FUNCTION ankheg_attack_waves
BEGIN
  LAUNCH_ACTION_FUNCTION check_ini
    STR_VAR
    ini		= "ankheg_waves_count"
    RET
    ankheg_waves_count		= value
  END

  LAUNCH_ACTION_FUNCTION check_ini
    STR_VAR
    ini		= "ankheg_waves_interval"
    RET
    ankheg_waves_interval	= value
  END

  LAUNCH_ACTION_FUNCTION clone_creature
    STR_VAR
    creature		= "ankheg=>mh#ankh3 ankheg=>mh#ankh4 ankheg=>mh#ankh5 ankheg=>mh#ankh6 ankheg=>mh#ankh7"
    editstring		= ~level1=>"object_index + 3" hitpoints=>"(object_index + 3) * 13 / 2" thac0=>"17 - object_index" enforce_saves=>at_best xp_value=>"object_index from [120 175 270 420 650]" dv=>"mh#SpawnedAnkheg"~
  END

  LAUNCH_ACTION_FUNCTION extend_area_script
    STR_VAR
    area		= "%FishingVillage_AnkhegPit%"
    bottom		= "spawn_random_ankhegs"
    location		= "scripts"
  END
END	// ankheg_attack_waves


