DEFINE_ACTION_FUNCTION gerde_fenten
BEGIN
  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    file	= "gerde_fenten.d"
    location	= "dialog"
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "%FishingVillage%"
    editstring	= ~delete_actor=>"actor_resource is_in [gerde ankhegg]"~
  END

  LAUNCH_ACTION_FUNCTION extend_area_script
    STR_VAR
    area	= "%FishingVillage%"
    bottom	= "spawn_gerde"
    location	= "scripts"
  END
END	// gerde_fenten


