DEFINE_ACTION_FUNCTION setup_firkraags_lair
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "custom_monsters"
    locbase	= "shared"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "windspear_hills"
    tra		= "windspear_hills"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "mist_cavern"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "main_complex"
  END
END	// setup_firkraags_lair


