DEFINE_ACTION_FUNCTION temple_grounds
BEGIN
  APPEND_COL "spawngrp.2da" "$ $ RDShwolf 20 shawol01 shawol01 shawol02 shawol01 shawol01 shawol02 * *" UNLESS "RDShwolf"

  MAKE_PATCH
    patch_spawn_inline=>~spawn_method=>1 spawn_maximum=>6 spawn_frequency=>50 spawn_count=>2 spawn_creature1=>"RDShad" spawn_creature2=>"RDShwolf"~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar1404"
    edits	= "patch_data"
  END
END	// temple_grounds


