DEFINE_ACTION_FUNCTION shadow_dragon_battle
BEGIN
  LAUNCH_ACTION_FUNCTION edit_creature
    STR_VAR
    creature	= "dragshad"
    editstring	= "strength=>25 intelligenceGT=>20 wisdomGT=>21 dexterityGT=>21 constitutionGT=>21 charismaGT=>21"
  END

  LAUNCH_ACTION_FUNCTION extend_area_script
    STR_VAR
    area	= "ar1402"
    bottom	= "spawn_shadow_dragon_minions"
    location	= "scripts"
  END
END	// shadow_dragon_battle


