DEFINE_ACTION_FUNCTION mist_cavern
BEGIN
  MAKE_PATCH
    patch_spawn_inline=>~spawn_method=>1 spawn_base_number=>20 spawn_maximum=>3 spawn_count=>2 spawn_creature1=>"RDMist1" spawn_creature2=>"RDMist2"~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar1201"
    edits	= "patch_data"
  END

  LAUNCH_ACTION_FUNCTION extend_area_script
    STR_VAR
    area	= "ar1201"
    bottom	= "ch6_spawns_mist"
    location	= "scripts"
  END
END	// mist_cavern


