DEFINE_ACTION_FUNCTION setup_bg2_vampires
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "custom_monsters"
    locbase	= "shared"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "ravenloft_stats"
    tra		= "bg2_vampires"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "dace_battle"
    tra		= "bg2_vampires"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "bodhis_lair"
    tra		= "bg2_vampires"
  END
END


