DEFINE_ACTION_FUNCTION cloakwood_assassins
BEGIN
  LAUNCH_ACTION_FUNCTION clone_item
    STR_VAR
    item	= "scrl3b=>mh#cwass"
    editstring	= "say_unidentified_description=>16"
  END

  LAUNCH_ACTION_FUNCTION install_creature
    STR_VAR
    creature	= "mh#drikx mh#gnung mh#strok"
    editstring	= ~say_both_names=>"object_index from [17 18 19]"~
  END

  LAUNCH_ACTION_FUNCTION compile_all
    STR_VAR
    location	= "compile_this"
  END
END	// cloakwood_assassins


