DEFINE_ACTION_FUNCTION setup_durlags_tower
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_custom_monsters"
    locbase	= "shared/custom_monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "astral_phase_spiders crypt_crawlers fell_ghasts tower_exterior upper_levels air_chamber earth_chamber lower_levels"
    tra		= "durlags_tower"
  END
END	// setup_durlags_tower


