DEFINE_ACTION_FUNCTION setup_durlags_tower
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_monsters"
    locbase	= "shared/monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "astral_phase_spiders crypt_crawlers fell_ghasts ghoul_lords tower_exterior upper_levels air_chamber earth_chamber fire_chamber lower_levels demon_knight"
    tra		= "durlags_tower"
  END
END	// setup_durlags_tower


