ACTION_CLEAR_ARRAY wraith_spider

ACTION_DEFINE_ASSOCIATIVE_ARRAY wraith_spider
BEGIN
  levelGT		=> "3 + %spider_hd_bonus%"
  enforce_hp		=> at_worst
  enforce_thac0		=> at_worst
  enforce_saves		=> at_worst
  hp_plus		=> 2
  enforce_xp		=> 6
  ac			=> "5 - %spider_ac_bonus%"
  ac_vs_missiles	=> "-2"
  general		=> undead
  resist_cold		=> 100
  resist_magic_cold	=> 100
  replace_items		=> "mh#spdwr(weapon1)"
END


