ACTION_CLEAR_ARRAY wraith_spider

ACTION_DEFINE_ASSOCIATIVE_ARRAY wraith_spider
BEGIN
  thac0			=> "17 - %spider_thac0_bonus%"
  ac			=> "5 - %spider_ac_bonus%"
  ac_vs_missiles	=> "-2"
  resist_crushing	=> "%spider_physical_resistance%"
  resist_piercing	=> "%spider_physical_resistance%"
  resist_slashing	=> "%spider_physical_resistance%"
  general		=> undead
  resist_cold		=> 100
  resist_magic_cold	=> 100
END


