DEFINE_ACTION_FUNCTION hairy_spider_swarm
BEGIN
  /*
  LAUNCH_ACTION_FUNCTION check_ini
    STR_VAR
    ini		= "hairy_spider_swarm_size"
    RET
    hairy_spider_swarm_size	= value
  END
  */

  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    file	= "mh#swmhs.baf"
    location	= "scripts"
  END

  LAUNCH_ACTION_FUNCTION clone_creature
    STR_VAR
    creature	= "cutspy=>mh#swmhs"
    editstring	= ~script_override=>"mh#swmhs" dv=>"mh#hairy_spider_swarm"~
  END
END	// hairy_spider_swarm


