DEFINE_ACTION_FUNCTION setup_magical_beasts
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_regeneration"
    locbase	= "shared/regeneration"
  END

  LAUNCH_ACTION_FUNCTION install_spell_pack
    STR_VAR
    spell_copy	= ""
    tra		= "magical_beasts"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "create_paws_and_scripts magical_beast_revisions relocate_bg1_winter_wolves"
    tra		= "magical_beasts"
  END
END	// setup_magical_beasts


