DEFINE_ACTION_FUNCTION entrance_tunnel
BEGIN
  MAKE_PATCH
    patch_spawn_inline=>~spawn_base_number=>100 spawn_maximum=>8~
    clone_spawn_inline=>~number_to_add=>3 match=>"spawn_xloc = 2663 and spawn_yloc = 1000" spawn_xloc=>"entry_index from [2418 3071 1950]"  spawn_yloc=>"entry_index from [648 1126 1328]"~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar6101"
    edits	= "patch_data"
  END
END	// entrance_tunnel


