IF
  See(NearestEnemyOf(Myself))
  !Range(LastSeenBy(Myself), 5)
THEN
  RESPONSE #70
  SelectWeaponAbility(SLOT_WEAPON0, 0)
  AttackReevaluate(LastSeenBy(Myself), 15)
  RESPONSE #30
  SelectWeaponAbility(SLOT_WEAPON1, 0)
  AttackReevaluate(LastSeenBy(Myself), 15)
END

IF
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself), 5)
THEN
  RESPONSE #70
  SelectWeaponAbility(SLOT_WEAPON1, 0)
  AttackReevaluate(LastSeenBy(Myself), 15)
  RESPONSE #30
  RunAwayFrom(LastSeenBy(Myself), 15)
END


