DEFINE_ACTION_FUNCTION setup_suldanessenar
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_monsters"
    locbase	= "shared/monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_high_level"
    locbase	= "shared/high_level"
  END


  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "black_dragon_battle"
    tra		= "suldanessenar"
  END
END	// setup_suldanessenar


