DEFINE_ACTION_FUNCTION setup_regeneration
BEGIN
  LAUNCH_ACTION_FUNCTION check_label
    STR_VAR
    label	= "mh#regeneration"
    RET
    installed	= value
  END

  ACTION_IF NOT installed
  BEGIN
    LAUNCH_ACTION_FUNCTION make_label
      STR_VAR
      label	= "mh#regeneration"
    END

    LAUNCH_ACTION_FUNCTION run
      STR_VAR
      file	= "regeneration_items regeneration_spells"
      locbase
    END
  END
END	// setup_regeneration


