DEFINE_ACTION_FUNCTION setup_underdark
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_new_monsters"
    locbase	= "shared/new_monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "kuotoa_levels"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "illithid_activities"
    tra		= "underdark"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "deirex_battle"
    tra		= "underdark"
  END
END	// setup_underdark


