DEFINE_ACTION_FUNCTION setup_underdark
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_new_animations"
    locbase	= "shared/new_animations"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_custom_monsters"
    locbase	= "shared/custom_monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "kuotoa_levels illithid_activities deirex_battle"
    tra		= "underdark"
  END
END	// setup_underdark


