DEFINE_ACTION_FUNCTION setup_underdark
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_animations"
    locbase	= "shared/animations"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_monsters"
    locbase	= "shared/monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "kuotoa_levels illithid_activities deirex_battle"
    tra		= "underdark"
  END
END	// setup_underdark


