ACTION_CLEAR_ARRAY ghast

ACTION_DEFINE_ASSOCIATIVE_ARRAY ghast
BEGIN
  resist_cold		=> "if resist_fire < 100 then 100 else no_change"
  resist_magic_cold	=> "if resist_magic_fire < 100 then 100 else no_change"
  attacks		=> 2
  replace_items		=> "mh#ghacl(weapon1) mh#ghacl(weapon2) mh#ghabt(shield)"
  strip_script		=> "ghast"
  insert_script_high	=> "mh#ghast"
  add_proficiencies	=> "2weapon=>3"
END


