DEFINE_ACTION_FUNCTION asylum_dungeon
BEGIN
  
  // AR1512 - Maze (starting level)

  MAKE_PATCH
    patch_spawn_inline=>~spawn_method=>1 spawn_maximum=>5 spawn_base_number=>20 spawn_count=>10 spawn_creature1=>"RDGolem" spawn_creature2=>"RDGolem2" spawn_creature3=>"RDGolem3" spawn_creature4=>"RDMist2" spawn_creature5=>"RDMist3" spawn_creature6=>"RDMephit" spawn_creature7=>"RDSlim2" spawn_creature8=>"RDSpid3" spawn_creature9=>"RDSpid4" spawn_creature10=>"RDSPid5"~
    patch_trigger_inline=>~match=>"trigger_script = spwnmon" trigger_script=>"spwngol"~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar1512"
    edits	= "patch_data"
  END


  // AR1514 - Maze (minotaur lair)

  LAUNCH_ACTION_FUNCTION edit_creature
    STR_VAR
    creature	= "icmin01"
    editstring	= ~level_all=>12 xp_value=>7000 enforce_hp=>at_worst enforce_thac0=>at_worst enforce_saves=>at_worst replace_items=>"ax1h02(weapon1)" immunity_to_opcode=>213~
  END

  MAKE_PATCH
    add_actor_inline'01=>~actor_name=>"{literal:Brass Minotaur}" actor_resource=>"mh#brass" actor_x_coord=>895 actor_y_coord=>1090 actor_orientation=>6~
    add_actor_inline'02=>~actor_name=>"{literal:Brass Minotaur}" actor_resource=>"mh#brass" actor_x_coord=>1545 actor_y_coord=>920 actor_orientation=>11~
    add_actor_inline'03=>~actor_name=>"{literal:Brass Minotaur}" actor_resource=>"mh#brass" actor_x_coord=>1595 actor_y_coord=>1635 actor_orientation=>1~
    add_actor_inline'04=>~actor_name=>"{literal:Brass Minotaur}" actor_resource=>"mh#brass" actor_x_coord=>1735 actor_y_coord=>1700 actor_orientation=>3~
    add_actor_inline'05=>~actor_name=>"{literal:Juggernaut Golem}" actor_resource=>"goljug01" actor_x_coord=>1895 actor_y_coord=>595 actor_orientation=>9~
    add_actor_inline'06=>~actor_name=>"{literal:Sand Golem}" actor_resource=>"golsan01" actor_x_coord=>2030 actor_y_coord=>675 actor_orientation=>7~
    add_actor_inline'07=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>2150 actor_y_coord=>1825 actor_orientation=>10~
    add_actor_inline'08=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>2255 actor_y_coord=>1865 actor_orientation=>8~
    add_actor_inline'09=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>2100 actor_y_coord=>1955 actor_orientation=>9~
    add_actor_inline'10=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>2405 actor_y_coord=>690 actor_orientation=>15~
    add_actor_inline'11=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>2495 actor_y_coord=>725 actor_orientation=>2~
    add_actor_inline'12=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>2315 actor_y_coord=>800 actor_orientation=>1~
    add_actor_inline'13=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>955 actor_y_coord=>1505 actor_orientation=>4~
    add_actor_inline'15=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>875 actor_y_coord=>1425 actor_orientation=>2~
    add_actor_inline'16=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>635 actor_y_coord=>1620 actor_orientation=>9~
    add_actor_inline'17=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>760 actor_y_coord=>1715 actor_orientation=>7~
    add_actor_inline'18=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>1630 actor_y_coord=>1240 actor_orientation=>11~
    add_actor_inline'19=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>1680 actor_y_coord=>1200 actor_orientation=>12~
    add_actor_inline'20=>~actor_name=>"{literal:Minotaur}" actor_resource=>"icmin01" actor_x_coord=>1725 actor_y_coord=>1255 actor_orientation=>10~


    patch_actor_inline'1=>~match=>"actor_resource = troll01" actor_name=>"{literal:Spirit Troll}" actor_resource=>"trolsi01"~
    patch_actor_inline'2=>~match=>"actor_resource = behgau01" actor_name=>"{literal:Observer}" actor_resource=>"behobs01"~

    patch_spawn_inline=>~spawn_method=>1 spawn_maximum=>5 spawn_base_number=>20 spawn_count=>10 spawn_creature1=>"RDGolem" spawn_creature2=>"RDGolem2" spawn_creature3=>"RDGolem3" spawn_creature4=>"RDMist2" spawn_creature5=>"RDMist3" spawn_creature6=>"RDMephit" spawn_creature7=>"RDSlim2" spawn_creature8=>"RDSpid3" spawn_creature9=>"RDSpid4" spawn_creature10=>"RDSPid5"~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar1514"
    edits	= "patch_data"
  END


  // AR1507 - Arbiter (kobold lair)

  LAUNCH_ACTION_FUNCTION clone_creature
    STR_VAR
    creature	= "skelwa03=>mh#sadet"
    editstring	= ~xp_value=>5000 replace_items=>"bow02(weapon1) sw2h02(weapon2) arow06(quiver1,x2) arow10(quiver2,x40) ring99(lring) immune1(rring)" animation=>"skeleton" dv=>"mh#sadet"~
  END

  LAUNCH_ACTION_FUNCTION clone_creature
    STR_VAR
    creature	= "skelwa03=>mh#sadis"
    editstring	= ~xp_value=>5000 replace_items=>"bow02(weapon1) sw2h02(weapon2) arow07(quiver1,x2) arow11(quiver2,x40) ring99(lring) immune1(rring)" animation=>"skeleton" dv=>"mh#sadis"~
  END

  MAKE_PATCH
    patch_actor_inline'1=>~match=>"actor_resource = elekob01" actor_name=>"{literal:Skeleton Archer (Detonation)}" actor_resource=>"mh#sadet"~
    patch_actor_inline'2=>~match=>"actor_resource = elehob01" actor_name=>"{literal:Skeleton Archer (Dispelling)}" actor_resource=>"mh#sadis"~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar1507"
    edits	= "patch_data"
  END

  COPY_EXISTING "ar1507.bcs" "override"
    DECOMPILE_AND_PATCH
    BEGIN
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
       "elekob01" "mh#sadet"
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
       "elehob01" "mh#sadis"
    END


  // AR1503 - Arbiter (fungus)

  MAKE_PATCH
    add_actor_inline'1=>~actor_name=>"{literal:Spore Colony}" actor_resource=>"icfung02" actor_x_coord=>535 actor_y_coord=>335 actor_orientation=>0~
    add_actor_inline'2=>~actor_name=>"{literal:Spore Colony}" actor_resource=>"icfung02" actor_x_coord=>700 actor_y_coord=>530 actor_orientation=>0~
    add_actor_inline'3=>~actor_name=>"{literal:Myconid King}" actor_resource=>"icmyc02" actor_x_coord=>675 actor_y_coord=>500 actor_orientation=>2~
    add_actor_inline'4=>~actor_name=>"{literal:Myconid King}" actor_resource=>"icmyc02" actor_x_coord=>560 actor_y_coord=>395 actor_orientation=>2~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar1503"
    edits	= "patch_data"
  END

  COPY_EXISTING "ar1503.bcs" "override"
    DECOMPILE_AND_PATCH
    BEGIN
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
       ~Dead("icfung02")~ ~NumDeadGT("icfung02", 2)~
    END


  // AR1506 - Arbiter (troll altar)

  MAKE_PATCH
    add_actor_inline'1=>~actor_name=>"{literal:Spirit Troll}" actor_resource=>"trolsi01" actor_x_coord=>910 actor_y_coord=>710 actor_orientation=>2~
    add_actor_inline'2=>~actor_name=>"{literal:Spirit Troll}" actor_resource=>"trolsi01" actor_x_coord=>1250 actor_y_coord=>775 actor_orientation=>3~
    add_actor_inline'3=>~actor_name=>"{literal:Giant Troll}" actor_resource=>"trolgi01" actor_x_coord=>1190 actor_y_coord=>655 actor_orientation=>1~
    add_actor_inline'4=>~actor_name=>"{literal:Giant Troll}" actor_resource=>"trolgi01" actor_x_coord=>1070 actor_y_coord=>855 actor_orientation=>1~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar1506"
    edits	= "patch_data"
  END


  // AR1515 - Asylum (first floor)

  MAKE_PATCH
    add_actor_inline'1=>~actor_name=>"{literal:Juggernaut Golem}" actor_resource=>"goljug01" actor_x_coord=>1365 actor_y_coord=>770 actor_orientation=>12~
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "ar1515"
    edits	= "patch_data"
  END
END	// asylum_dungeon


