DEFINE_ACTION_FUNCTION setup_amkethran
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_monsters"
    locbase	= "shared/monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "elder_elementals"
    locbase	= "shared/monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "elemental_tables mercenary_battles vongoethe_battle"
    tra		= "amkethran"
  END
END	// setup_amkethran


