DEFINE_ACTION_FUNCTION bg2_dragons
BEGIN
  // Red Dragon in Windspear Hills (Firkraag)

  LAUNCH_ACTION_FUNCTION extend_area_script
    STR_VAR
    area	= "ar1203"
    bottom	= "spawn_firkraag_minions"
    location	= "scripts"
  END


  // Shadow Dragon in Temple Ruins

  LAUNCH_ACTION_FUNCTION extend_area_script
    STR_VAR
    area	= "ar1402"
    bottom	= "spawn_shadow_dragon_minions"
    location	= "scripts"
  END
END	// bg2_dragons


