DEFINE_ACTION_FUNCTION setup_graveyard
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "setup_new_monsters"
    locbase	= "shared/new_monsters"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "northern_tomb"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "southern_tomb"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "bodhis_lair"
  END
END	// setup_graveyard


