DEFINE_ACTION_FUNCTION adamantite_golem
BEGIN
  MAKE_PATCH
    strength=>25
    resist_slashing=>95
    resist_crushing=>95
    resist_piercing=>95
    resist_missile=>95
    resist_acid=>0
    resist_electricity=>0
    strength=>24
    dexterity=>17
    constitution=>20
    intelligence=>9
    wisdom=>2
    charisma=>7
    replace_items=>"immune4(rring)"
  END

  LAUNCH_ACTION_FUNCTION edit_creature
    STR_VAR
    creature	= "golada01 golkill2"
  END
END	// adamantite_golem


