BEGIN_ACTION_DEFINITION
Name(FrostBreath)
TRIGGER
  See(scstarget)
  Range(LastSeenBy(Myself), 10)
  !GlobalTimerNotExpired("frost_breath", "locals")
ACTION	
  RESPONSE #scsprob1
    SetGlobalTimer("frost_breath", "locals", TEN_ROUNDS)
    FaceObject(scstarget)
    ReallyForceSpell(scstarget, WINTER_WOLF_BREATH)
END

IF TRIGGER
  TriggerBlock(Enemy|AoECold)
  TargetBlock(PCsPreferringStrong)
  TargetBlock(EnemiesInReverseOrder)
THEN DO
  Action(FrostBreath|40|60)
END


