DEFINE_ACTION_FUNCTION elder_elementals
BEGIN
  // Elder Air/Earth/Fire Elementals (20 hd elementals)

  MAKE_PATCH
    level1=>20
    xp_value=>15000
    hitpoints=>160
    thac0=>1
    enforce_saves=>at_worst
    say_both_names=>"object_index from [38 39 40 41]"
    dv=>DEST_RES
  END

  LAUNCH_ACTION_FUNCTION clone_creature
    STR_VAR
    creature	= "elairg01=>elaire01 elearg01=>eleare01 elfirg01=>elfire01 elwatg01=>elwate01"
    edits	= "patch_data"
  END
END	// elder_elementals


