DEFINE_ACTION_FUNCTION water_elementals
BEGIN
  // Water Elementals (8/12 hd elementals)

  MAKE_PATCH
    level1=>"object_index from [8 12]"
    thac0=>"21 - level1"
    hitpoints=>"level1 * 8"
    xp_value=>"(level1 - 5) * 1000"
    enforce_saves=>always
    say_both_names=>"object_index from [13 14]"
    dv=>DEST_RES
  END

  LAUNCH_ACTION_FUNCTION clone_creature
    STR_VAR
    creature	= "elwatg01=>elwatl01 elwatg01=>elwat01"
    edits	= "patch_data"
  END
END	// water_elementals


